import Scheme3

-- Inspect every theorem's logical dependencies. No sorryAx is permitted.
#print axioms Scheme3.block_roundtrip
#print axioms Scheme3.result_bind_ok
#print axioms Scheme3.result_bind_error
#print axioms Scheme3.result_map_ok
#print axioms Scheme3.result_map_error
#print axioms Scheme3.result_pure
#print axioms Scheme3.result_throw
#print axioms Scheme3.scalar_zero_rejected
#print axioms Scheme3.scalar_order_rejected
#print axioms Scheme3.scalar_max_accepted
#print axioms Scheme3.firstScalar_mem
#print axioms Scheme3.reduction_bounded
#print axioms Scheme3.initial_candidate
#print axioms Scheme3.last_candidate
#print axioms Scheme3.no_scalar_search_exhausted
#print axioms Scheme3.all_rejected_exhausts
#print axioms Scheme3.delegation_covers_boundary
#print axioms Scheme3.delegated_length
#print axioms Scheme3.delegation_window_count
#print axioms Scheme3.keygen_rejects_delegation
#print axioms Scheme3.keygen_length_rejected
#print axioms Scheme3.announce_length_rejected
#print axioms Scheme3.meta_wire_length
#print axioms Scheme3.metadata_wire_length
#print axioms Scheme3.announcement_wire_length
#print axioms Scheme3.metadata_tag_first
#print axioms Scheme3.parse_meta_wrong_length
#print axioms Scheme3.parse_announcement_wrong_length
#print axioms Scheme3.parse_point_roundtrip
#print axioms Scheme3.parse_announcement_roundtrip
#print axioms Scheme3.bind_generated
#print axioms Scheme3.bind_accepts_same_ek
#print axioms Scheme3.match_complete
#print axioms Scheme3.match_sound
#print axioms Scheme3.scan_sound
#print axioms Scheme3.scan_complete
#print axioms Scheme3.scan_accepts_iff
#print axioms Scheme3.tag_mismatch_skips
#print axioms Scheme3.address_mismatch_skips
#print axioms Scheme3.foreign_scheme_skips
#print axioms Scheme3.unregistered_scheme_skips
#print axioms Scheme3.receiver_agreement
#print axioms Scheme3.honest_payment
#print axioms Scheme3.zero_sum_rejected
#print axioms Scheme3.master_recovery
#print axioms Scheme3.fresh_extension
#print axioms Scheme3.drawIndex_advances
#print axioms Scheme3.drawIndex_exhausted
